name: Test

on: [push, pull_request]


permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.21', '1.22']
    name: Go ${{ matrix.go }}
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ matrix.go }}
      - name: Download gomodules
        run: go mod download
      - name: Run tests
        run: go test -v ./...
        env:
          AWS_ACCESS_KEY_ID: AKID
          AWS_SECRET_ACCESS_KEY: SECRET

